### ISSUE TITLE
Feature request: Key bind to toggle shotgun/super shotgun like PC version

### ISSUE THREAD

**Issue by Dragonsbrethren** [BodbDearg/PsyDoom#46] opened 2022-09-07 14:10 UTC
Years of playing Doom on PC means weapon switching has become muscle memory. It's currently not possible to copy the PC version's controls exactly because it isn't possible to map the shotgun and super shotgun to the same key. An optional toggle bind like the fist/chainsaw already have would solve this and stop players from fumbling for the right weapon!

**Comment by BodbDearg** [comment] 2022-09-08 02:49
Dupe of #23. See that ticket for my thoughts on this.

**Closed by BodbDearg** 2022-09-08 02:49 UTC
Labels: enhancement, wontfix
