### ISSUE TITLE
PC Weapon Binding option?

### ISSUE THREAD

**Issue by ASLB247** [BodbDearg/PsyDoom#110] opened 2024-03-16 04:05 UTC
Is there any way to make it so the super shotgun and normal shotgun share the 3 key and all other weapons are moved back one like in the pc doom? (Chaingun at 4, rocket launcher at 5, etc.)

It just feels so weird to play doom where the shotgun and super shotgun are separate keys unless I’m using a controller.

**Comment by fenderc01** [comment] 2024-03-16 15:51
See https://github.com/BodbDearg/PsyDoom/issues/23

**Comment by BodbDearg** [comment] 2024-05-25 04:57
Closing as dupe of #23.

**Closed as not planned** 2024-05-25 05:47 UTC
Labels: duplicate, enhancement
