### ISSUE TITLE
Option to swap between SG and SSG with Slot 3 key

### ISSUE THREAD

**Issue by OpenRift412** [BodbDearg/PsyDoom#25] opened 2021-12-12 01:49 UTC
Just a quality of life option that would feel more consistent with PC Doom and PC ports of Doom 64.

**Comment by BodbDearg** [comment] 2021-12-16 06:25
Thank you for the suggestion! This issue has been raised previously by https://github.com/BodbDearg/PsyDoom/issues/23. See comments in that ticket for my thoughts on this.

**Comment by BodbDearg** [comment] 2021-12-16 06:25
Closing as a duplicate of #23.

**Closed by BodbDearg** 2021-12-16 06:25 UTC

**Comment by OpenRift412** [comment] 2021-12-16 23:28
> Thank you for the suggestion! This issue has been raised previously by #23. See comments in that ticket for my thoughts on this.

I see. Well, you wouldn't necessarily _have_ to change the HUD elements or shift any of the existing weapon binds, it could just be an optional toggle for those who want it. It could co-exist with the dedicated SG and SSG keys instead of replacing them. It seems a bit silly to even have dedicated weapon binds in the first place if that's the case.
