### ISSUE TITLE
Bug: fix tabing out of the port

### ISSUE THREAD

**Issue by Akis-02** [BodbDearg/PsyDoom#38] opened 2022-07-16 22:18 UTC
You cant alt tab while you use the port which is a bit obnoxious, so adding it would be nice, maybe even a windowed mode

**Comment by BodbDearg** [comment] 2022-09-12 08:37
Thanks for the report - just reproduced on my own machine. Looks like it happens if you alt-tab out while in the automap specifically, other parts of the game don't have this issue.

**Comment by getphobo** [comment] 2022-09-13 01:02
Hi,
I have a similar issue. I currently play on a machine where the integrated Intel Graphics is the only GPU.

Alt-tabbing only works properly if you alt-tab out of the game, then alt-tab back to the game, then alt-tab out of the game again. Otherwise, if you don't double alt-tab as described, the game's viewport will be in front, blocking other windows.

**Comment by BodbDearg** [comment] 2022-10-01 06:25
This bug should be fixed as of 1.0.0.

**Closed** 2022-10-01 06:25 UTC
Labels: bug
