### ISSUE TITLE
[Bug] Monsters Sometimes Get Stuck on Nightmare

### ISSUE THREAD

**Issue by fenderc01** [BodbDearg/PsyDoom#81] opened 2022-12-18 17:17 UTC
I noticed that sometimes monsters can get stuck upon seeing the player when playing nightmare, but not other difficulties. I can't say I've seen it happen a lot, but I noticed it on Final Doom MAP03: Canyon in the small slime room with the cacodemons and the spectre. The spectre gets stuck, but I can free him if I shoot him.

**Comment by BodbDearg** [comment] 2022-12-23 18:26
It's probably due to a combination of higher movement speed of some enemies on Nightmare and the limitations of Doom's AI. Enemies don't ever move partial steps, so in space constrained situations the extended movement step size for NM might make the enemy overshoot and keep trying to move into positions that are not allowed. If it turns out to be that and not something else I'll likely close this as 'won't fix' since reworking Doom's AI is not something I would consider for this project.

**Comment by BodbDearg** [comment] 2023-02-12 09:37
Yeah, confirmed it's the added movement speed for NM which is the issue. Even on ultra violence (or lower) however this particular monster in the situation described gets semi-stuck; it can't advance towards the player due to space constraints, only backwards towards the window. The map design is the real problem in this particular case.

One fix for this issue might be to do a half (or even quarter) movement step if a full one fails but I'm not a fan of this solution because it affects the AI too much; it seems to cause enemies to hug corners far more often instead of changing direction (did a quick experiment).

This bug should only affect Demons since they are the only monster which get a speed boost on NM and should only be a problem in a few tricky cases. Because a potential fix affects the AI behavior too much, and because the problem is fairly limited and harmless I'm going to close this as a 'won't fix'.

**Closed by BodbDearg** 2023-02-12 09:37 UTC
Labels: bug
