### ISSUE TITLE
PsyDoom doesn't save launcher's files if user's Windows profile title has cyrillic symbols in it

### ISSUE THREAD

**Issue by pepsican64** [BodbDearg/PsyDoom#105] opened 2023-10-13 20:43 UTC
Hey thank you for your contributions to the DOOM community I really appreciate it...

The title is pretty much self-explanatory, but i'll give some details anyway

1, The PsyDoom settings folder just doesn't creates.
2. When launcher opens, every setting automatically resets to default.
3. When PsyDoom tries to record the demo by setting "record demo" option in launcher, the game crashes with "unable to record the demo file" error.
4. The game launches without any issues. The path to .cue file set in launcher is read by game like there's not issue presented.

That's everything I found out so far. I dunno how will PsyDoom act when the players hosts / connects to server, but I think the game will act normal without any issues.

btw, sorry for my not so good english, its not my native lang and I dont know much about it, you know.

**Comment by BodbDearg** [comment] 2023-11-13 06:19
Hello @pepsican64 thanks for reporting this issue. Can you confirm which version of PsyDoom you are using?

There was a similar issue fixed for [1.1.1](https://github.com/BodbDearg/PsyDoom/releases/tag/releases%2F1.1.1). If you are not using 1.1.1 then it might be fixed by upgrading. Otherwise this might be a new problem which needs to be investigated...

**Comment by pepsican64** [comment] 2023-11-13 15:11
hey @BodbDearg nice to see your answer

i'm using the latest 1.1.1, x86-64 version that was released on the june 13th.

i dunno, maybe the problem happens cos im using the very dated unupdated and unsupported windows 7 7601 build. anyway, hope you'll find the fix soon.

**Comment by BodbDearg** [comment] 2023-11-15 07:14
Thanks for confirming, will have a look into it.

**Comment by BodbDearg** [comment] 2024-08-29 06:50
Tried to reproduce the issue against PsyDoom 1.1.1 on Windows 11 with a user name containing the characters `жлфы`. Everything appeared to be working as expected, including the saving of Launcher preferences, save games etc.

Maybe it is an issue specific to Windows 7 as you suggest. I would be curious to see if the same problem still happens on Windows 8.1. I'm pretty confident that Windows 10 should work OK since the fix previously mentioned (which was added to 1.1.1) was originally developed and tested against Windows 10.

Closing this issue out for now since it is not really actionable on my part. If new information becomes available then I can take a look again.

**Closed as completed by BodbDearg** 2024-08-29 06:50 UTC
Labels: bug
